spring:
  application:
    name: weather-guard
    id: VNG-1000001
  webflux:
    base-path: /vanguard
  datasource:
    url: jdbc:h2:mem:weatherdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
#      path: /h2-console
#      port: 8082
      settings:
        web-allow-others: false
  management:
    server.port: 9090
    endpoints:
      web:
        exposure.include: info, health, h2console

server:
  servlet:
    context-path: /vanguard

external:
  openweather:
    endpoint: https://api.openweathermap.org
    path: /data/2.5/weather?q=%s,%s&appid=%s
    apiKey: ENC(4vM6+SknJd7R4Zj70dsuWN8N5tfW6fKuR5gler79r8Kl4UemckoI+EADxsokuM0iH7AHKo3MHCPVKtB0cA+k9KUzSSYwXvNX9TsRyRWYfos=)
    timeoutInSeconds: 3
  authhub:
    tokens: sampletoken1, sampletoken2, sampletoken3, sampletoken4, sampletoken5

infrastructure:
  rate:
    limit:
      seconds: 3600
      requests: 5

jasypt:
  encryptor:
    password: e.dfjksdifj+dj
    algorithm: PBEWithHMACSHA512AndAES_256
